/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aerobalamdevs.Ventana;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;



/**
 *
 * @author annelis
 */
public class InicioSesionAdministracion extends javax.swing.JFrame {

    Administración administracion = new Administración();
    
    /**
     * Creates new form InicioSesionAdministracion
     */
    public InicioSesionAdministracion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public InicioSesionAdministracion(JButton jButtonIngresar, JButton jButtonRegresar, JComboBox<String> jComboBoxTIpoUsuario, JLabel jLabelContraseña, JLabel jLabelFondo, JLabel jLabelTIpo, JLabel jLabelTitulo, JLabel jLabelUsuario, JPasswordField jPasswordFieldCampoContraseña, JTextField jTextFieldCampoUsuario) {
        this.jButtonIngresar = jButtonIngresar;
        this.jButtonRegresar = jButtonRegresar;
        this.jComboBoxTIpoUsuario = jComboBoxTIpoUsuario;
        this.jLabelContraseña = jLabelContraseña;
        this.jLabelFondo = jLabelFondo;
        this.jLabelTIpo = jLabelTIpo;
        this.jLabelTitulo = jLabelTitulo;
        this.jLabelUsuario = jLabelUsuario;
        this.jPasswordFieldCampoContraseña = jPasswordFieldCampoContraseña;
        this.jTextFieldCampoUsuario = jTextFieldCampoUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRegresar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jTextFieldCampoUsuario = new javax.swing.JTextField();
        jLabelTIpo = new javax.swing.JLabel();
        jPasswordFieldCampoContraseña = new javax.swing.JPasswordField();
        jComboBoxTIpoUsuario = new javax.swing.JComboBox<>();
        jButtonIngresar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegresar.setBackground(new java.awt.Color(0, 0, 255));
        jButtonRegresar.setFont(new java.awt.Font("Yrsa Medium", 2, 18)); // NOI18N
        jButtonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 370, 120, -1));

        jLabelTitulo.setFont(new java.awt.Font("Yrsa Medium", 2, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 0, 0));
        jLabelTitulo.setText("Iniciar Sesión");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 220, -1));

        jLabelUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setFont(new java.awt.Font("Yrsa Medium", 2, 24)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jLabelUsuario.setText("Usuario:");
        getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 110, -1));

        jLabelContraseña.setBackground(new java.awt.Color(255, 255, 255));
        jLabelContraseña.setFont(new java.awt.Font("Yrsa Medium", 2, 24)); // NOI18N
        jLabelContraseña.setForeground(new java.awt.Color(0, 0, 0));
        jLabelContraseña.setText("Contraseña:");
        getContentPane().add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));
        getContentPane().add(jTextFieldCampoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 133, 180, 30));

        jLabelTIpo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTIpo.setFont(new java.awt.Font("Yrsa Medium", 2, 24)); // NOI18N
        jLabelTIpo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTIpo.setText("Tipo:");
        getContentPane().add(jLabelTIpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 80, -1));
        getContentPane().add(jPasswordFieldCampoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 201, 180, 30));

        jComboBoxTIpoUsuario.setFont(new java.awt.Font("Yrsa Medium", 2, 18)); // NOI18N
        jComboBoxTIpoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Depto. Administración", "Agencia de Aerolinea", "Operador de Vuelos" }));
        jComboBoxTIpoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxTIpoUsuarioMouseClicked(evt);
            }
        });
        jComboBoxTIpoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTIpoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxTIpoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 190, -1));

        jButtonIngresar.setBackground(new java.awt.Color(204, 255, 51));
        jButtonIngresar.setFont(new java.awt.Font("Yrsa Medium", 2, 24)); // NOI18N
        jButtonIngresar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonIngresar.setText("Ingresar");
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 120, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerobalamdevs/Imagenes/InicioSesion.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
     // Llamamos al JFrame anterior para poder regresar
        
        Inicio vistaInicio2 = new Inicio();
        vistaInicio2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jComboBoxTIpoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTIpoUsuarioActionPerformed
    /**
     * @param TipoUsuario vamos a dividir el ComboBox para que 
     * cuando se inicie sesion se tenga la opción de elegir y poder
     * llamarl las demás ventanas dependiendo la opción elegida
     */
  
    
    }//GEN-LAST:event_jComboBoxTIpoUsuarioActionPerformed

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        
     /**
     * @param Opcion vamos a crear un metodo que me compare 
     * la seleccion elegida en el ComboBoxTIpoUsuario para que
     * especificamente se abra la venta que corresponde y para ello
     * se hara un if como condicional
     */
  
        
        String Opcion  = (String)jComboBoxTIpoUsuario.getSelectedItem();
         if ("Depto. Administración".equals(Opcion)) {
            Administración administracion = new Administración();
            administracion.setVisible(true);
        this.dispose();
        } else if ("Agencia de Aerolinea".equals(Opcion)) {
         GerenciaAerolinea aerolinea = new GerenciaAerolinea();   
         aerolinea.setVisible(true);
         this.dispose();
        } else if ("Operador de Vuelos".equals(Opcion)) {
          OperadorVuelo operador = new OperadorVuelo();
          operador.setVisible(true);
          this.dispose();
        }
      
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jComboBoxTIpoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTIpoUsuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTIpoUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesionAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesionAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesionAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesionAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesionAdministracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JComboBox<String> jComboBoxTIpoUsuario;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTIpo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jPasswordFieldCampoContraseña;
    private javax.swing.JTextField jTextFieldCampoUsuario;
    // End of variables declaration//GEN-END:variables
}
